### ISSUE TITLE
File not found error - 1_Miami,_FL_Office_1_report.html

### ISSUE THREAD

**Issue by vishjo** [LBNL-JCI-ICF/better#14]
I do have existing python@v3.8. I use VScode for coding. 

I tried to run the code @run.py and it looks like in report.py with function generate_building_report_beta is not able to find "1_Miami,_FL_Office_1_report.html" file.
![Error_better_tool](https://user-images.githubusercontent.com/67727139/86440593-5cb61600-bd28-11ea-89b6-d1122b787e48.png)

**Comment by alejo101** [comment]
In 'demo.py', at the top where 'data_path' and 'report_path' are defined, change the forward slashes of '/Data/' and '/outputs/' to double backward slashes so that it looks like \\Data\\ and \\outputs\\. That should fix it.

**Comment by jenishp619** [comment]
I am still facing error tried \\data\\ and \\outputs\\ any reason why that html report file is not generated?

**Comment by jenishp619** [comment]
@alejo101 @vishjo @tsbyq   In addition to that the error is about the use of , in the file name that you can see on the final report_file "1_Miami,_FL_office_1_report.html" so you need to add this code - report_file = report_file.replace(',', '') before writing report html code. I have resolved this issue today admin can close this issue
